"""transform betwen FoodItems and food_category

Revision ID: 52f783bf780f
Revises: f799aa4e5901
Create Date: 2025-08-03 17:03:08.418249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f783bf780f'
down_revision = 'f799aa4e5901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=200), nullable=False))
        batch_op.drop_constraint(batch_op.f('food_category_rate_it_fkey'), type_='foreignkey')
        batch_op.drop_column('rate_it')
        batch_op.drop_column('name')

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('rate_it', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'food_items', ['rate_it'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rate_it')
        batch_op.drop_column('name')

    with op.batch_alter_table('food_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rate_it', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('food_category_rate_it_fkey'), 'food_items', ['rate_it'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###
