"""Add role_updated_at column to users

Revision ID: 569b04827331
Revises: df1b02a362f7
Create Date: 2025-08-06 02:19:40.675168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569b04827331'
down_revision = 'df1b02a362f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role_updated_at')

    # ### end Alembic commands ###
