"""transform betwen FoodItems and food_category and fix

Revision ID: 65aa769249e1
Revises: 52f783bf780f
Create Date: 2025-08-03 17:06:20.287741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aa769249e1'
down_revision = '52f783bf780f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('food_items_rate_it_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'food_category', ['rate_it'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('food_items_rate_it_fkey'), 'food_items', ['rate_it'], ['id'])

    # ### end Alembic commands ###
