"""transform betwen FoodItems and food_category and fix

Revision ID: df1b02a362f7
Revises: 65aa769249e1
Create Date: 2025-08-03 18:22:07.088884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1b02a362f7'
down_revision = '65aa769249e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_category_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('food_items_rate_it_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'food_category', ['food_category_id'], ['id'])
        batch_op.drop_column('rate_it')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_it', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('food_items_rate_it_fkey'), 'food_category', ['rate_it'], ['id'])
        batch_op.drop_column('food_category_id')

    # ### end Alembic commands ###
